sudo: false

env:
  global:
  - secure: 2Sdk/yAm79iNRpN6U3CT83nDbdeR740lwHLQIoOKGi7jxphWbKq3JNjj2f1Fa4X13sc8yKfEfdQzLSwZVch1fxG4Ib4uzb3RqtH9g0Yf63shl/6EMJE+p83EktNse6BMgSSAkLxruVPE9m7yptmQ0ydlHbO7DLchaTbRs1C73N4=
  - secure: HMGkDgbay0TcQtiCm5K4F1Y8trtMT5X5S8nRGrTrKBuI4RIEkTQ06VdQVf96gnhe/7IjDQfAUbXWspSmlpWbIKij4BRHOijezU37sooNUkQp4R+EfPpbJECnuv+4WqZI2bMj2i3sw3b8f1oNCFztzHrpxZQ9oOeQbenf/8c2fQs=
  - secure: huLKjE7xlxl7HaCLIIVyDaZN9ZsWrR4RcxW+JNUH1F9lM5mbRjAPayawSKRzHViu7u6uUNkjMOJs3lRlWdj8ezH2vnJNm9oNvCOYuSFmBIBELVlXcfbqpX9ZffbJeFiUZ2dOwrDEhm3+WIg6Wr3QbUtVdlMfNvljOJ3CQQc9Yc4=
  - secure: Jr+6c6pF5H0lP4Kt6evlf/xYD/Qjoms3HK7lw1kg8lzwoEXPD3MezgkpOktU8ZBllGolc+ou23h+3hgJwvqi7ANmjzfxyVDdpB7Kiw4y2pEm6tAXYzmatSDb401u7+2sb2H/aSe8yikNrVrizvqaJrDOGeptCBjXQF+a2lNeMC0=
  - secure: hzJKtjqujadYb7QiMhCLCieNtTp77aMRaqxorJq2+CT+dMcIh1S/S9jxXsfl4OzidnIv2QHussHo5gOdS3U4JzRsHEgQ5+4HRkpxif1UijVqb4FXgaaS3PuBylV2xtMAlVjOUW+HqSCVxbokhrqWkeTKEozfk18+E8TnuOqhKjU=

language: cpp
matrix:
  include:
  - compiler: ": Linux, ocaml 4.02.1, opam 1.2.0"
    os: linux
    env: OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0
  - compiler: ": Mac, ocaml 4.02.1, opam 1.2.0"
    os: osx
    env: OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0

addons:
  apt:
    packages:
    - libelf-dev
    - aspcud

before_install: bash -e resources/travis/before_install.sh
install: bash -e resources/travis/install_deps.sh
script: bash -e resources/travis/build.sh
before_deploy: bash -e resources/travis/before_deploy.sh

cache:
  directories:
  - "$HOME/.flow_cache"
  - "$HOME/.yarn-cache"
  - node_modules
  - resources/travis/node_modules
  - src/parser/node_modules

before_cache:
- rm -rf $HOME/.flow_cache/ocaml-*/.opam/log

deploy:
- provider: releases
  api_key:
    secure: HMMxgYX2qHFn6Sphg+qmEP1QFTL9R9cN+oJIqPcFBpDG4Gt4sbZEHU7PNtwxZpJ/SyiMcMfLAkyIk1cUc35ye4YQqbkeVuA/oevGs2/Zr9VcK4CeHwja7Bf/HRa3GXqyN9uymcDHA/dflkXZ8BdfFIJlvSaFr7+xrGUYilja9RInki76+c+N9+6HKFZOl4nM+cIAxv5UGaM2Xs8hdiBlmqsnyfypYexRBup5lPt4ozVxWhrmbPTHRrVeTbo04YbfCvSC5iyXt2ZzzOkEzYiTl8gpLGjzf5LOiQqAu0Zfh7m7Nza1ODeQdcSTAllw7QipsdcAksgle69riF7V0nkXwll8i52F15K2O7TeLuTA5J4CxkTn1KCyWzMu15vvhxIvYcKmeU8nPbywCV2jTw9fFUClXTQkTYXsys00fa2OEg/DTAHbDp57QO9p/LT6akxWsidx9FROk30enPcNX1EfYoCZdkffNbxp+PpAZabzmQNC1xcYLWOYaEgv/mvYH/OeG+yCBt7+VcfBHF1w/bAct3QSH67kW/FCb4/XyVo9X18H1xigXMrZAllqrB9+H0QRr4CxoWzP8eze9DjhArT5TZRUb8bSizqM67EwH9QAjONnLDeHJKVae3Bnzwd9dvWGtoah192bks/4Ek9vrvWJF2Gwot/8CVoLx5b5d2rIFlk=
  repo: pvolok/flow
  skip_cleanup: true
  file_glob: true
  file: flow-*.zip
  on:
    tags: true
    all_branches: true
    condition:
    - "$OCAML_VERSION = 4.02.1"
    - "$OPAM_VERSION = 1.2.0"
